services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    container_name: frontend_container
    ports:
      - "3000:3000"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:latest
    container_name: backend_container
    ports:
      - "5000:5000"

